-- ============================================================
--  Miralocks — Configuration MASTER COMPLÈTE
--  Version : 6.0 (Mise à jour du 31/03/2026)
--  Reflète l'état exact de la base de données en production
--
--  Tables     : settings, site_settings, blog_posts,
--               galerie_photos, galerie_videos, avis_clients,
--               services, rendezvous, admin_2fa, admin_logs,
--               historique, visites
--  Storage    : bucket Miralocks-media (dossier rendezvous/)
--  Edge Fns   : send-confirmation (v2), send-reminders (v1)
--  Cron       : rappels-rdv-quotidiens (08:00 UTC = 09:00 Lomé)
-- ============================================================


-- ══════════════════════════════════════════════════════════════
-- 1. TABLES
-- ══════════════════════════════════════════════════════════════

-- Paramètres site (ancienne table)
CREATE TABLE IF NOT EXISTS public.settings (
  cle        TEXT PRIMARY KEY,
  valeur     TEXT,
  modifie_le TIMESTAMPTZ DEFAULT NOW()
);

-- Paramètres site (nouvelle table utilisée par supabase.js)
CREATE TABLE IF NOT EXISTS public.site_settings (
  id         TEXT PRIMARY KEY,
  valeur     TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Blog
CREATE TABLE IF NOT EXISTS public.blog_posts (
  id         BIGSERIAL PRIMARY KEY,
  titre      TEXT NOT NULL,
  extrait    TEXT,
  contenu    TEXT,
  photo_url  TEXT,
  categorie  TEXT DEFAULT 'Conseil',
  slug       TEXT,
  publie     BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Galerie photos
CREATE TABLE IF NOT EXISTS public.galerie_photos (
  id          BIGSERIAL PRIMARY KEY,
  titre       TEXT,
  description TEXT,
  photo_url   TEXT NOT NULL,
  categorie   TEXT DEFAULT 'creation',
  ordre       INTEGER DEFAULT 0,
  publie      BOOLEAN DEFAULT true,
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- Galerie vidéos
CREATE TABLE IF NOT EXISTS public.galerie_videos (
  id            BIGSERIAL PRIMARY KEY,
  titre         TEXT NOT NULL,
  description   TEXT,
  video_url     TEXT NOT NULL,
  thumbnail_url TEXT,
  publie        BOOLEAN DEFAULT true,
  created_at    TIMESTAMPTZ DEFAULT NOW()
);

-- Avis clients
CREATE TABLE IF NOT EXISTS public.avis_clients (
  id         BIGSERIAL PRIMARY KEY,
  nom        TEXT NOT NULL,
  localite   TEXT DEFAULT 'Lomé, Togo',
  etoiles    SMALLINT DEFAULT 5 CHECK (etoiles >= 1 AND etoiles <= 5),
  texte      TEXT NOT NULL,
  approuve   BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Services / Prestations
CREATE TABLE IF NOT EXISTS public.services (
  id          BIGSERIAL PRIMARY KEY,
  nom         TEXT NOT NULL,
  description TEXT,
  prix        TEXT,
  categorie   TEXT DEFAULT 'Autres',
  ordre       INTEGER DEFAULT 0,
  actif       BOOLEAN DEFAULT true,
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- Rendez-vous
CREATE TABLE IF NOT EXISTS public.rendezvous (
  id                 BIGSERIAL PRIMARY KEY,
  nom                TEXT NOT NULL,
  tel                TEXT NOT NULL,
  email              TEXT,
  service            TEXT NOT NULL,
  date_rdv           DATE NOT NULL,
  heure              TEXT,
  message            TEXT,
  photo_url          TEXT,
  statut             TEXT DEFAULT 'en_attente'
                     CHECK (statut IN ('en_attente','confirme','annule','termine')),
  note_admin         TEXT,
  whatsapp_callmebot TEXT,
  callmebot_apikey   TEXT,
  created_at         TIMESTAMPTZ DEFAULT NOW()
);

-- Authentification 2FA admin
CREATE TABLE IF NOT EXISTS public.admin_2fa (
  id         BIGSERIAL PRIMARY KEY,
  email      TEXT NOT NULL,
  code       TEXT NOT NULL,
  attempts   INTEGER DEFAULT 0,
  used       BOOLEAN DEFAULT false,
  expires_at TIMESTAMPTZ DEFAULT (NOW() + INTERVAL '10 minutes'),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Logs d'actions admin
CREATE TABLE IF NOT EXISTS public.admin_logs (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  user_email TEXT,
  action     TEXT NOT NULL,
  details    TEXT
);

-- Historique des actions admin (section Historique du site)
CREATE TABLE IF NOT EXISTS public.historique (
  id         BIGSERIAL PRIMARY KEY,
  type       TEXT NOT NULL,   -- rdv | blog | galerie | avis | service | connexion | autre
  message    TEXT NOT NULL,
  detail     TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);


-- Visites du site (tracking des pages vues)
CREATE TABLE IF NOT EXISTS public.visites (
  id         BIGSERIAL PRIMARY KEY,
  page       TEXT NOT NULL DEFAULT '/',
  referrer   TEXT,
  user_agent TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_visites_date ON public.visites (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_visites_page ON public.visites (page);

-- ══════════════════════════════════════════════════════════════
-- 2. PERMISSIONS (GRANTS)
-- ══════════════════════════════════════════════════════════════

GRANT SELECT, INSERT ON public.avis_clients  TO anon;
GRANT SELECT, INSERT ON public.rendezvous    TO anon;
GRANT SELECT ON public.blog_posts            TO anon;
GRANT SELECT ON public.galerie_photos        TO anon;
GRANT SELECT ON public.galerie_videos        TO anon;
GRANT SELECT ON public.services              TO anon;
GRANT SELECT ON public.settings              TO anon;
GRANT SELECT ON public.site_settings         TO anon;
GRANT INSERT ON public.visites               TO anon;
GRANT USAGE, SELECT ON SEQUENCE visites_id_seq TO anon;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon;
GRANT ALL ON ALL TABLES    IN SCHEMA public TO authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO authenticated;


-- ══════════════════════════════════════════════════════════════
-- 3. ROW LEVEL SECURITY (RLS)
-- ══════════════════════════════════════════════════════════════

ALTER TABLE public.blog_posts     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.galerie_photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.galerie_videos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.avis_clients   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rendezvous     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.services       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_settings  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_logs     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.historique     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.visites        ENABLE ROW LEVEL SECURITY;
-- admin_2fa : RLS désactivé volontairement (géré par Edge Function)

-- Blog
DROP POLICY IF EXISTS "read_public_blog" ON public.blog_posts;
DROP POLICY IF EXISTS "admin_all_blog"   ON public.blog_posts;
CREATE POLICY "read_public_blog" ON public.blog_posts
  FOR SELECT USING (publie = true);
CREATE POLICY "admin_all_blog"   ON public.blog_posts
  FOR ALL USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- Galerie photos
DROP POLICY IF EXISTS "read_public_galerie" ON public.galerie_photos;
DROP POLICY IF EXISTS "admin_all_galerie"   ON public.galerie_photos;
CREATE POLICY "read_public_galerie" ON public.galerie_photos
  FOR SELECT USING (publie = true);
CREATE POLICY "admin_all_galerie"   ON public.galerie_photos
  FOR ALL USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- Galerie vidéos
DROP POLICY IF EXISTS "read_public_videos" ON public.galerie_videos;
DROP POLICY IF EXISTS "admin_all_videos"   ON public.galerie_videos;
CREATE POLICY "read_public_videos" ON public.galerie_videos
  FOR SELECT USING (publie = true);
CREATE POLICY "admin_all_videos"   ON public.galerie_videos
  FOR ALL USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- Avis clients
DROP POLICY IF EXISTS "read_public_avis"   ON public.avis_clients;
DROP POLICY IF EXISTS "insert_public_avis" ON public.avis_clients;
DROP POLICY IF EXISTS "admin_all_avis"     ON public.avis_clients;
CREATE POLICY "read_public_avis"   ON public.avis_clients
  FOR SELECT USING (approuve = true);
CREATE POLICY "insert_public_avis" ON public.avis_clients
  FOR INSERT WITH CHECK (true);
CREATE POLICY "admin_all_avis"     ON public.avis_clients
  FOR ALL USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- Rendez-vous
DROP POLICY IF EXISTS "insert_public_rdv" ON public.rendezvous;
DROP POLICY IF EXISTS "admin_all_rdv"     ON public.rendezvous;
CREATE POLICY "insert_public_rdv" ON public.rendezvous
  FOR INSERT WITH CHECK (true);
CREATE POLICY "admin_all_rdv"     ON public.rendezvous
  FOR ALL USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- Services
DROP POLICY IF EXISTS "public_read_services"    ON public.services;
DROP POLICY IF EXISTS "admin_all_services_total" ON public.services;
CREATE POLICY "public_read_services"     ON public.services
  FOR SELECT USING (true);
CREATE POLICY "admin_all_services_total" ON public.services
  FOR ALL USING (auth.role() = 'authenticated')
  WITH CHECK (true);

-- Settings (ancienne table)
DROP POLICY IF EXISTS "read_public_settings" ON public.settings;
DROP POLICY IF EXISTS "admin_all_settings"   ON public.settings;
CREATE POLICY "read_public_settings" ON public.settings
  FOR SELECT USING (true);
CREATE POLICY "admin_all_settings"   ON public.settings
  FOR ALL USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- Site settings (nouvelle table)
DROP POLICY IF EXISTS "read_public_site_settings" ON public.site_settings;
DROP POLICY IF EXISTS "admin_all_site_settings"   ON public.site_settings;
CREATE POLICY "read_public_site_settings" ON public.site_settings
  FOR SELECT USING (true);
CREATE POLICY "admin_all_site_settings"   ON public.site_settings
  FOR ALL USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- Logs admin
DROP POLICY IF EXISTS "Admins can do everything on logs" ON public.admin_logs;
CREATE POLICY "Admins can do everything on logs" ON public.admin_logs
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Historique du site
DROP POLICY IF EXISTS "admin_all_historique" ON public.historique;
DROP POLICY IF EXISTS "public_insert_historique" ON public.historique;
CREATE POLICY "admin_all_historique" ON public.historique
  FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "public_insert_historique" ON public.historique
  FOR INSERT WITH CHECK (true);


-- Visites
DROP POLICY IF EXISTS "insert_public_visite" ON public.visites;
DROP POLICY IF EXISTS "admin_read_visites"   ON public.visites;
CREATE POLICY "insert_public_visite" ON public.visites
  FOR INSERT WITH CHECK (true);
CREATE POLICY "admin_read_visites" ON public.visites
  FOR SELECT USING (auth.role() = 'authenticated');

-- ══════════════════════════════════════════════════════════════
-- 4. STORAGE
-- Bucket "Miralocks-media" : créer manuellement via
--   Supabase Dashboard → Storage → New bucket → Public ✅
--   Types autorisés : image/jpeg, image/png, image/webp,
--                     image/gif, image/avif, video/mp4, video/webm
-- ══════════════════════════════════════════════════════════════

-- Lecture publique de tous les fichiers du bucket
DROP POLICY IF EXISTS "lecture_publique_storage" ON storage.objects;
CREATE POLICY "lecture_publique_storage" ON storage.objects
  FOR SELECT USING (bucket_id = 'Miralocks-media');

-- Upload public uniquement dans le dossier rendezvous/
-- (utilisé par sb.publicUpload('rendezvous', file) dans supabase.js)
DROP POLICY IF EXISTS "envoi_publique_rdv" ON storage.objects;
CREATE POLICY "envoi_publique_rdv" ON storage.objects
  FOR INSERT WITH CHECK (
    bucket_id = 'Miralocks-media'
    AND (storage.foldername(name))[1] = 'rendezvous'
  );

-- Accès total pour l'admin authentifié (tous les dossiers)
DROP POLICY IF EXISTS "admin_total_storage" ON storage.objects;
CREATE POLICY "admin_total_storage" ON storage.objects
  FOR ALL
  USING (bucket_id = 'Miralocks-media' AND auth.role() = 'authenticated')
  WITH CHECK (bucket_id = 'Miralocks-media' AND auth.role() = 'authenticated');


-- ══════════════════════════════════════════════════════════════
-- 5. ANTI-SPAM (TRIGGERS)
-- ══════════════════════════════════════════════════════════════

-- Avis : maximum 15 soumissions par heure
CREATE OR REPLACE FUNCTION public.check_avis_limit()
RETURNS TRIGGER AS $$
BEGIN
  IF (
    SELECT count(*) FROM public.avis_clients
    WHERE created_at > NOW() - INTERVAL '1 hour'
  ) >= 15 THEN
    RAISE EXCEPTION 'Trop d''avis soumis. Réessayez plus tard.';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_avis_limit ON public.avis_clients;
CREATE TRIGGER trigger_avis_limit
  BEFORE INSERT ON public.avis_clients
  FOR EACH ROW EXECUTE FUNCTION public.check_avis_limit();

-- Rendez-vous : maximum 2 demandes par jour par numéro de téléphone
CREATE OR REPLACE FUNCTION public.check_rdv_limit()
RETURNS TRIGGER AS $$
BEGIN
  IF (
    SELECT count(*) FROM public.rendezvous
    WHERE tel = NEW.tel AND created_at > NOW() - INTERVAL '1 day'
  ) >= 2 THEN
    RAISE EXCEPTION 'Trop de demandes. Réessayez demain.';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_rdv_limit ON public.rendezvous;
CREATE TRIGGER trigger_rdv_limit
  BEFORE INSERT ON public.rendezvous
  FOR EACH ROW EXECUTE FUNCTION public.check_rdv_limit();


-- ══════════════════════════════════════════════════════════════
-- 6. INDEX (Performances)
-- ══════════════════════════════════════════════════════════════

CREATE INDEX IF NOT EXISTS idx_rdv_date        ON public.rendezvous (date_rdv DESC);
CREATE INDEX IF NOT EXISTS idx_rdv_statut      ON public.rendezvous (statut);
CREATE INDEX IF NOT EXISTS idx_services_ord    ON public.services   (ordre ASC);
CREATE INDEX IF NOT EXISTS idx_blog_date       ON public.blog_posts (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_historique_date ON public.historique (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_historique_type ON public.historique (type);


-- ══════════════════════════════════════════════════════════════
-- 7. CRON JOB — Rappels WhatsApp 24h avant le RDV
--    Déclenchement : 08:00 UTC = 09:00 heure de Lomé (GMT+1)
-- ══════════════════════════════════════════════════════════════

CREATE EXTENSION IF NOT EXISTS pg_cron;

SELECT cron.schedule(
  'rappels-rdv-quotidiens',
  '0 8 * * *',
  $$
    SELECT net.http_post(
      url     := 'https://mqityrifhiaarwdcacxo.supabase.co/functions/v1/send-reminders',
      headers := '{"Content-Type":"application/json","apikey":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xaXR5cmlmaGlhYXJ3ZGNhY3hvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQxMTYwMDEsImV4cCI6MjA4OTY5MjAwMX0.sYsUB9AWPXrsRDnz8YxEQiZOh7USxP2W_QNrZyU3mpE"}'::jsonb,
      body    := '{}'::jsonb
    );
  $$
);


-- ══════════════════════════════════════════════════════════════
-- 8. EDGE FUNCTIONS (déployées via Supabase CLI)
-- ══════════════════════════════════════════════════════════════
-- send-confirmation (v2) — ACTIVE
--   → Email de confirmation au client + notification admin
--   → Appelée depuis rendezvous.html après sauvegarde du RDV
--   → verify_jwt : false (appelée avec anon key)
--
-- send-reminders (v1) — ACTIVE
--   → Rappels WhatsApp CallMeBot chaque matin à 09h (Lomé)
--   → Déclenchée par le cron job ci-dessus
--   → verify_jwt : false
-- ══════════════════════════════════════════════════════════════
